# Generated by Django 5.1.6 on 2025-02-16 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'block', 'verbose_name_plural': 'blocks'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'currency', 'verbose_name_plural': 'currencies'},
        ),
    ]
